export { default as Icon } from './Icon/index.vue'
export { registerIcons } from './Icon/registry'
export type { IconRegistry } from './Icon/registry'
export { default as LocaleDropdown } from './LocaleDropdown/index.vue'
export type { LocaleOption } from './LocaleDropdown/types'
export { default as ThemeSwitch } from './ThemeSwitch/index.vue'
